### ISSUE TITLE
Rename intro.Rmd to NHSRplotthedots.Rmd

### ISSUE THREAD

**Issue by francisbarton** [nhs-r-community/NHSRplotthedots#225]
This will make the intro vignette appear in the pkgdown site navbar automatically as "Get started".

[link](https://pkgdown.r-lib.org/reference/build_articles.html#get-started)

Otherwise I think we should sort the articles nav menu list so that 'intro' is at the top.

If we move it to the navbar as its own 'Get started' item, I think the current 3 other vignettes are probably OK in the order they're already in (alphabetical). Otherwise we could explictly reorder them in `_pkgdown.yml` with:

```
articles:
- title: Articles
  navbar: ~
  contents:
  - number-of-points-required
  - deviations
  - other-spc-tools
```
